language: python
python:
  - "3.6"
cache: pip
install:
  - pip install requests

# command to install dependencies

script:
  - python main.py

notifications:
  email:
    on_success: never
    on_failure: never
